### ISSUE TITLE
Self Signed Certificates

### ISSUE THREAD

**Issue by keverw** [andrewrk/node-s3-client#101]
I'm using Riak CS, a S3 Compatible API to run a local S3 Server while testing. I can connect using Transmit and the server is working fine. But when I try to use this module to connect using code I get 

```
unable to sync: Error: self signed certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1000:38)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._finishInit (_tls_wrap.js:567:8)
```

It'd be nice for `s3.createClient` to allow you to pass in a option to allow self signed or invalid certs while doing testing.

I was looking for workarounds and `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";` before starting the S3 Client didn't want to work. Anyone know of a workaround? Seems like the only thing todo is openup node.js in the aws-sdk dependencies and do `rejectUnauthorized: true` to false but I'd hate to have to do that everything there's an update

**Comment by faceleg** [comment]
I'd be open to accepting a PR that adds this functionality, but the core goal of this module is to support S3, not third party services.

**Comment by keverw** [comment]
Nice. Not sure if this could be done in this module directly, or if `aws-sdk` part would require the change instead. So far directly modifying it as a workaround, it works but I think it should really be a configurable option. Not sure if I would use Riak CS in production yet, but having a local server is useful for testing/development since my upload speed isn't the greatest.

**Comment by keverw** [comment]
After doing some more digging, found out under s3Options I can pass in my own sslAgent! :) So this allows me to use the module without editing the code for the module directly. So I'm pretty happy about that.

Here's how I did it, hopfully this will help anyone else if they ran into this problem:

```
function mySSLAgent()
	{
		var https = require('https');
		var agent = new https.Agent({
			rejectUnauthorized: false //changed to false, different from the default one
		});

		// delegate maxSockets to globalAgent
		Object.defineProperty(agent, 'maxSockets', {
			enumerable: true,
			get: function() { return https.globalAgent.maxSockets; }
		});

		return agent;
	}
```

then for the `s3.createClient` part, I added `httpOptions: {agent: mySSLAgent()}` after `secretAccessKey` and reverted my modified version of the module, and it worked perfectly :)

**Comment by faceleg** [comment]
Glad you found a way!
