### ISSUE TITLE
Setting permissions

### ISSUE THREAD

**Issue by fmmsilva** [andrewrk/node-s3-client#102]
How to set public access permission to files uploaded to the bucket?

**Comment by faceleg** [comment]
I think you'll find the answer in this portion: https://github.com/andrewrk/node-s3-client#clientuploadfileparams

That links to http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property, where I see the line `ACL: 'private | public-read | public-read-write | authenticated-read | bucket-owner-read | bucket-owner-full-control',`

**Comment by vmdao** [comment]
Thank @faceleg  👍 
And  you can read sollution add "Bucket Policy" in S3
flow https://github.com/aws/aws-sdk-js/issues/256#issuecomment-229301444
