### ISSUE TITLE
Provide url to uploaded file

### ISSUE THREAD

**Issue by dimhold** [andrewrk/node-s3-client#14]
Hi @andrewrk 

Can you, please, return your previous very useful api feature: url in the `end` event. I guess it can look something like that:

```
var uploader = client.uploadFile(params);
uploader.on('end', function(data) {
  console.log("done uploading. File available at " + data.url);
});
```

**Comment by OKNoah** [comment]
Does ` s3.getPublicUrl` still work? I see not a function error.
