### ISSUE TITLE
EISDIR: illegal operation on a directory

### ISSUE THREAD

**Issue by celicoo** [andrewrk/node-s3-client#146]
I'm trying to download an object in my bucket, but I can't use async because this error keeps showing up:

`EISDIR: illegal operation on a directory`

Does someone know what is going on? This error is old, I saw previous issues about it. Should I change the package? I can't understand how someone creates something that peoples depends and just to maintain.

**Comment by emilguareno** [comment]
What does your params object look like? I was getting this error because I wasn't specifying the file name when downloading a file. I thought that by specifying a folder name, the library would automatically fill in the key name as the file name, but that's not the case.
