### ISSUE TITLE
uploadDir skip some files

### ISSUE THREAD

**Issue by KromDaniel** [andrewrk/node-s3-client#149]
Hey, 
I'm using `"s3": "4.4.0"` and trying to upload folder with project after webpack
and for some reason it is skipping `bundle.js` files and `dist` sub-directory

Please let me know what else info I can provide.

**Comment by dallasread** [comment]
Having the same issue with dist/vendor.js using the same version. Were you able to resolve?

**Comment by dallasread** [comment]
The 'end' event seems to be firing too early. I'm going to just going to do some logic around 'fileUploadStart' & 'fileUploadEnd' to trigger 'done' more correctly.

**Comment by molszanski** [comment]
Here is a way to make it work. 
https://github.com/andrewrk/node-s3-client/issues/74
https://github.com/andrewrk/node-s3-client/issues/152

**Comment by dallasread** [comment]
Beauty. I'll check it out some time. A little more duct tape never hurt no one.
