### ISSUE TITLE
DeprecationWarning: Calling an asynchronous function without callback is deprecated.

### ISSUE THREAD

**Issue by mblarsen** [andrewrk/node-s3-client#164]
Getting this when running `uploadFile`

DeprecationWarning: Calling an asynchronous function without callback is deprecated. 

Maybe related to #145 (not the mime part but the graceful-fs part)

Node version: 7.6
Lib version: 4.4.0

**Comment by fishcharlie** [comment]
Any updates on this? Getting this same thing.

**Comment by mblarsen** [comment]
@fishcharlie not to my knowledge. Have you tried to use https://nodejs.org/api/cli.html#cli_trace_warnings to spot the issue?

```
node --trace-warnings script.js
```

**Comment by mblarsen** [comment]
The issue seems resolved, I'll close. Feel free to open if you still have it.
