### ISSUE TITLE
How i can exclude files for synchronise?

### ISSUE THREAD

**Issue by TTATPuOT** [andrewrk/node-s3-client#218]
Hello!
How i can exclude some types of files for synchronise folders?
On mac any folder has system file ".DS_Store", but how i can exclude it and upload all files without ".DS_Store"?

**Comment by ddoice** [comment]
Some pending PR opened in 2014 and last commit 2 years ago this repo looks pretty dead.

I needed to ignore some files so i created a new PR  #220 and a npm [package](https://www.npmjs.com/package/@ddoice/s3) patched, you can install it with 

```
npm i -S @ddoice/s3
```
then use it
```
const s3 = require("@ddoice/s3");

const params = {
   ...
   ignoreFiles: ['report.html','stats.json']
};

```
