### ISSUE TITLE
How do it set header while uploading file

### ISSUE THREAD

**Issue by anilalgoworks** [andrewrk/node-s3-client#82]
i want to upload media on s3 with following headers  " cache-control and expires ".
How can we acheive this in your module?

**Comment by dingledow** [comment]
:+1: for this issue @andrewrk

**Comment by faceleg** [comment]
You can apply any of the properties described here: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property

Found this by reading the readme, specifically: https://github.com/andrewrk/node-s3-client#clientuploadfileparams
