### ISSUE TITLE
S3 uploaddir() not working for large no of files

### ISSUE THREAD

**Issue by sachin-gill** [andrewrk/node-s3-client#95]
We are using the API to upload a directory containing about 39k files. The total size of the folder is about 260MB. The upload process terminates after uploading about 2.5k files without any error or completion. Its aborts randomly. The majority of files are small in size.
Can you confirm is this a known issue.
Thanks

**Comment by fallanic** [comment]
looks like I'm experiencing the same issue

**Comment by adamtsai1** [comment]
I am experiencing this issue as well.

**Comment by dvalentiate** [comment]
this issue should be fixed with pull request #110 or #130 .

**Comment by faceleg** [comment]
Merged #130
