### ISSUE TITLE
client.downloadStream() never emit a 'end' event

### ISSUE THREAD

**Issue by rodrigoalviani** [andrewrk/node-s3-client#98]
Events like 'error' and 'httpHeaders' works, but 'end', 'finish', 'close', 'progress', whatever not work.
How to use returned stream?

**Comment by rodrigoalviani** [comment]
My bad, I need to use the stream created when httpHeaders.statusCode = 200.
Now works...

**Comment by faceleg** [comment]
:dancer: thanks for reporting back!
